"""Configuration constants for firmware skeleton."""

from constants import (
	DEFAULT_HEARTBEAT_INTERVAL,
	DEFAULT_MEASUREMENT_INTERVAL,
	DEFAULT_MQTT_KEEPALIVE,
	DEFAULT_DS18B20_PIN,
)

# Device
DEVICE_ID = "esptesst-001"

# WiFi
WIFI_SSID = "Orange_Swiatlowod_8AB2_2.4GHz"
WIFI_PASSWORD = "ASYNNVH5YU3L"

# MQTT
MQTT_HOST = "192.168.1.51"
MQTT_PORT = 1883
MQTT_USER = ""
MQTT_PASSWORD = ""
MQTT_KEEPALIVE = DEFAULT_MQTT_KEEPALIVE
MQTT_CLIENT_ID = DEVICE_ID

# Backward-compatible aliases
MQTT_BROKER = MQTT_HOST
MQTT_USERNAME = MQTT_USER
MQTT_TOPIC_BASE = "frigomonitor/devices/" + DEVICE_ID
MQTT_TOPIC_HEARTBEAT = MQTT_TOPIC_BASE + "/heartbeat"
MQTT_TOPIC_MEASUREMENTS = MQTT_TOPIC_BASE + "/measurements"

# Intervals
HEARTBEAT_INTERVAL_S = DEFAULT_HEARTBEAT_INTERVAL
MEASUREMENT_INTERVAL_S = DEFAULT_MEASUREMENT_INTERVAL
MAIN_LOOP_DELAY_S = 1

# Locale
TIMEZONE = "UTC"

# Sensor calibration
TEMPERATURE_OFFSET_C = 0.0
DS18B20_PIN = DEFAULT_DS18B20_PIN

# Watchdog
WATCHDOG_TIMEOUT_MS = 30000

# Logging
DEBUG_ENABLED = True
