"""Shared firmware constants for ESP32 modules."""

DEFAULT_WIFI_TIMEOUT = 20
WIFI_POLL_INTERVAL_MS = 200

DEFAULT_MQTT_KEEPALIVE = 60
MAIN_LOOP_SLEEP_MS = 100

DEFAULT_DS18B20_PIN = 4
DS18B20_CONVERSION_TIME_MS = 750
DS18B20_INVALID_HIGH_C = 85.0
DS18B20_INVALID_LOW_C = -127.0

MQTT_STATUS_TOPIC_TEMPLATE = "frigomonitor/device/{device_id}/status"
MQTT_HEARTBEAT_TOPIC_TEMPLATE = "frigomonitor/device/{device_id}/heartbeat"
MQTT_STATUS_ONLINE = "online"
MQTT_STATUS_OFFLINE = "offline"

DEFAULT_HEARTBEAT_INTERVAL = 30
DEFAULT_MEASUREMENT_INTERVAL = 30

LOG_DEBUG = 10
LOG_INFO = 20
LOG_WARNING = 30
LOG_ERROR = 40
